### ISSUE TITLE
[Enhancement] Add --interactive flag for an interactive experience

### ISSUE THREAD

**Issue by MartinIngesen** [emtunc/SlackPirate#11]
Hi!

I suggest adding a `--interactive` flag which would make it even easier to go from cookie -> token -> scanning/dumping.

`python SlackPirate.py --interactive` and/or `python SlackPirate.py --interactive --cookie COOKIE`

```
$ python SlackPirate.py --interactive
Give me a cookie: <input cookie here> (providing the script with --interactive --cookie would skip this step)
This cookie has access to the following workspaces:
[0] https://example.slack.com
[1] https://example2.slack.com
[2] https://example3.slack.com
Select which workspace(s) to dump: <input number(s), either a single number or comma separated>

Select what you want to dump:
[A] All
[0] Dump team access logs in .json format if the token provided is a privileged token
[1] Dump the user list in .json format
[2] Find references to S3 buckets
[3] Find references to passwords and other credentials
[4] Find references to AWS keys
[5] Find references to private keys
[6] Find references to interesting URLs and links
Input: <input A for all, a single number or comma separated numbers for multiple>
```

The tool would then create individual folders for each workspace (like it does today) and use each token to do the dumping/scanning on each workspace.

**Comment by emtunc** [comment]
This looks really good! I'll try and make some time to look into this in the next couple of weeks.

**Comment by influenza** [comment]
I think this feature might pair nicely with restructuring the code to support loading it as a module during a python session (another feature I'm interested in). @MartinIngesen if you want to make a branch, I'll hop on and contribute!

**Comment by kmmanoj** [comment]
@emtunc I can help reformat the code to enable this feature. I have been passively following this issue. 
To start with, I shall submit a UML class diagram representing the reformation.
@influenza It would be great if you could support me in redesigning it. Thanks for the help!

**Comment by kmmanoj** [comment]
![SlackPirate](https://user-images.githubusercontent.com/16622304/75090924-d6c1db80-558d-11ea-8fb9-e968750aa588.jpeg)
Here is the design, please review if I missed any feature.

**Comment by emtunc** [comment]
Thanks @Robtova! This is now in https://github.com/emtunc/SlackPirate/releases/tag/0.20
