### ISSUE TITLE
user-list.json is not a valid array of JSON objects

### ISSUE THREAD

**Issue by milangfx** [emtunc/SlackPirate#12]
In dump_user_list(...) the r['members'] are appended to the outfile without any separation.

Putting "[ ]" around outfile to create an array and replacing every "}{" with "},{" solves this issue.
I don't know if it's best to append the commas inside the loop or do the replacing when the loop has finished.

**Comment by influenza** [comment]
May I suggest that we collect the individual objects into a result array, then use python's provided json serialization to ensure a valid object is produced

**Comment by emtunc** [comment]
Yes you're right - the code doesn't dump in an RFC compliant format. Forgive my ignorance but it seems that `},{` also isn't compliant with the RFC? It looks like we need to separate the individual objects with a comma `,` only?

I'll look in to JSON serialization as I am not too familiar with it.

**Comment by influenza** [comment]
To your first point, two adjacent objects in an array would indeed cause `},{`. Consider the following:
object 1: `{"name":"albert"}`
object 2: `{"name":"betty"}`

An array of the two would serialize as: `[{"name":"albert"},{"name":"betty"}]`

Regarding JSON serialization, I would consider using the built in functionality of the `requests` module to collect dictionaries into an array, then serialize that array to your output file. That would lead to a json blob that could be loaded by other tools later.

Something like:

```python
import json
#...
results = []
# Inside the loop
    results.append(response_obj.json())
   # Then to write the file:
   serialized_json = json.dumps(results)
```

Here's another example of using json.dumps:

```python
>>> arr = [dict(name=x) for x in ['alice', 'bob', 'mallory']]
>>> arr
[{'name': 'alice'}, {'name': 'bob'}, {'name': 'mallory'}]
>>> import json
>>> json.dump
json.dump(   json.dumps(
>>> json.dumps(arr)
'[{"name": "alice"}, {"name": "bob"}, {"name": "mallory"}]'
```

See http://docs.python-requests.org/en/master/user/quickstart/#json-response-content

```python
>>> import requests

>>> r = requests.get('https://api.github.com/events')
>>> r.json()
[{u'repository': {u'open_issues': 0, u'url': 'https://github.com/...
```

**Comment by emtunc** [comment]
Fixed!
