### ISSUE TITLE
[Enhancement] Asynchronous HTTP requests

### ISSUE THREAD

**Issue by emtunc** [emtunc/SlackPirate#4]
Currently the script performs HTTP requests synchronously - although there are Slack API rate limits in place, there are certain functions and calls that can benefit greatly by introducing asynchronous requests.

For example:

- File downloads - there is no need to wait for each file to download before moving on to the next. Also, as far as I can tell, there is no rate limit in place for file downloads. No reason why this function couldn't start asynchronously with the other functions in the script

- The cookie check and Workspace token grabbing feature - again, no reason why we can't make requests to the Workspace URLs all in one go rather than one at a time. On average it takes around 1 second per Workspace * total number of Workspaces to get all tokens back. This could be reduced to a couple of seconds for a large number of Workspaces.

I may need some assistance with this but in the mean time I will try and play around with some of the recommended async packages.

**Comment by influenza** [comment]
Here's one resource you may find helpful -> https://www.terriblecode.com/blog/asynchronous-http-requests-in-python/
