### ISSUE TITLE
Error: download_interesting_files fails in the page_counts_by_query.items() loop when the API rate limit is hit 

### ISSUE THREAD

**Issue by westonlit** [emtunc/SlackPirate#40]
START: Attempting to locate and download interesting files (this may take some time)
INFO: Slack API rate limit hit - sleeping for 60 seconds
Traceback (most recent call last):
  File "./SlackPirate.py", line 831, in <module>
    scan(token=provided_token, scan_context=collected_scan_context)
  File "./SlackPirate.py", line 664, in download_interesting_files
    new_files = [new_file for new_file in response_json['files']['matches'] if
KeyError: 'files'

**Comment by emtunc** [comment]
Thank you @westonlit ! Appreciate you spending your time looking at this. I've merged this along with a fix for the token lookup (--cookie flag) as I didn't realise Slack made changes to the frontend which stopped returning the XOX token #42
