### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by Pilly170** [emtunc/SlackPirate#45]
Hi,
Is it possible for passwords, aws keys, urls and s3 to have where they've come from added to the text doc?
Its awesome having a list, but I need to track down the users/channels that these relate to

Thanks

**Comment by Pilly170** [comment]
Ah the prefix is the channel.
Maybe then an outputted list of channels so I can correlate

**Comment by emtunc** [comment]
@Pilly170 might be a bit late for you but if you still use SlackPirate, have a go with the latest release and use the --verbose flag.

Let us know if there is anything you'd like to see that might be missing.
