### ISSUE TITLE
[Enhancement] Provide a list of user-agent strings rather than hard-coding

### ISSUE THREAD

**Issue by emtunc** [emtunc/SlackPirate#5]
Rather than hard-coding the user agent strings (which can be detected easily by the Blue team/detect function within a few weeks when everyone has moved on to a newer version of Chrome/Slack), provide a large-ish(?) list of user agent strings.

Maybe even hook in to a user-agent API to randomly select a relatively active/popular user-agent?

Worth thinking about

**Comment by NotoriousRebel** [comment]
I can work on this, we currently do something very similar for a tool called theHarvester.

**Comment by emtunc** [comment]
Thanks @NotoriousRebel ! This is complete now: #8
