### ISSUE TITLE
Cookie-based Slack enumeration is likely broken

### ISSUE THREAD

**Issue by cdanis** [emtunc/SlackPirate#54]
Sometime in the past week, Slack seems to have drastically changed the formatting of the "login to other slacks" page that is displayed when you access a Slack you don't have access to (like `slackpirate-donotuse.slack.com`).  Now, instead of the other Slacks being actual HTML entities, they seem to be created by Javascript.

I updated my re-implementation of this technique like so: https://github.com/cdanis/emojifs/commit/95190f9c1024cf4911c96ea4f0d2c5f73a88383a

**Comment by emtunc** [comment]
Thank you @cdanis ! I've fixed in https://github.com/emtunc/SlackPirate/commit/e93c58b88a40a8535bf9fcd536291c3193142aa5

I give it a couple weeks before they change the page structure again :-D
