### ISSUE TITLE
[Enhancement] Keep list of downloaded files and don't re-download them

### ISSUE THREAD

**Issue by emtunc** [emtunc/SlackPirate#9]
Currently if the script makes a query for 'password' and finds a file `file1.pdf` and makes another query for 'passwords' and finds the same file `file1.pdf`, it will download the file twice.

It should be possible to keep a list of file_id's and only download when the file_id is not in the list.

Should be fairly easy to implement I think.

**Comment by mikailtunc** [comment]
This was addressed in https://github.com/emtunc/SlackPirate/commit/9d80969172be41de9930e3ad8075f8453ecf2f32 👍
